application: maddenwg
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico  

- url: /.*
  script: main.app

libraries:
- name: PIL
  version: "1.1.7"
  
- name: jinja2
  version: latest
